config/routes.rb
Rails.application.routes.draw do

  resources :apps 

#  root 'versions#index'
  root 'apps#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app.rb
class App < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
    @app = App.all
  end

  def show
    @app = App.find(params[:id])
  end

  def new
    
  end

  def create
    @app = App.new(app_params)
    @app.save
    redirect_to @app
  end

  private
    def app_params
      params.require(:app).permit(:name,:ip,:command)
    end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/apps/index.html.erb
<h1>Listing Applications</h1>

<%= link_to 'New Application', new_app_path %>
 
<table>
  <tr>
    <th>Application</th>
    <th>IP</th>
    <th>Command</th>
  </tr>
 
  <% @app.each do |app| %>
    <tr>
      <td><%= app.name %></td>
      <td><%= app.ip %></td>
      <td><%= app.command %></td>
      <td><%= link_to 'Show', app_path(app) %></td>
    </tr>
  <% end %>
</table>

app/views/apps/new.html.erb
<h1>New Application</h1>

<%= form_with scope: :app, url: apps_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :ip %><br>
    <%= form.text_field :ip %>
  </p>
  <p>
    <%= form.label :command %><br>
    <%= form.text_field :command %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p>
  <strong>Application Name:</strong>
  <%= @app.name %>
</p>
 
<p>
  <strong>IP Address:</strong>
  <%= @app.ip %>
</p>

<p>
  <strong>Command:</strong>
  <%= @app.command %>
</p>

<%= link_to 'Back', apps_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Versionsdashboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/versions/index.html.erb
<h1>Versions Dashboard</h1>

<%= link_to 'My apps', controller: 'apps' %>